
CREATE TABLE [dbo].[Lesson](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Lectures] [nvarchar](50) NOT NULL,
	[Proffesor_Id] [int] NOT NULL,
 CONSTRAINT [PK_Lesson] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Lesson]  WITH CHECK ADD  CONSTRAINT [FK_Lesson_Proffesor] FOREIGN KEY([Proffesor_Id])
REFERENCES [dbo].[Proffesor] ([Id])
GO

ALTER TABLE [dbo].[Lesson] CHECK CONSTRAINT [FK_Lesson_Proffesor]
GO
