//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2017.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllAnswer
    {
        public int Id { get; set; }
        public int AllQuest_Id { get; set; }
        public string Answers { get; set; }
        public int right_Answ_id { get; set; }
    
        public virtual AllQuestion AllQuestion { get; set; }
    }
}
