//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2017.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AllQuestion()
        {
            this.AllAnswers = new HashSet<AllAnswer>();
        }
    
        public int Id { get; set; }
        public int Theme_id { get; set; }
        public string Question { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllAnswer> AllAnswers { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
