//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2017.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stud_attendance
    {
        public int Id { get; set; }
        public int stud_id { get; set; }
        public int attendance { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
