//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2017.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stud_Answers
    {
        public int Id { get; set; }
        public int stud_id { get; set; }
        public int theme_id { get; set; }
        public int answer_percent { get; set; }
        public System.DateTime answer_data { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
