//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2017.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudAnswers_live
    {
        public int Id { get; set; }
        public Nullable<int> Stud_Id { get; set; }
        public Nullable<int> Question_Id { get; set; }
        public Nullable<int> Stud_Answer { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
